"""add index on jobs.document_id

Revision ID: dd9d906eb477
Revises: bca0aee0a513
Create Date: 2026-03-08 15:51:59.310585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9d906eb477'
down_revision: Union[str, Sequence[str], None] = 'bca0aee0a513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    # ### end Alembic commands ###
